### ISSUE TITLE
Update APM names in language files

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#78]
https://github.com/checkout/link_checkoutcom/blob/1c152dae3763d30dddcd7694f1bd022ddb81de93/Cartridges/int_checkoutcom/cartridge/templates/resources/cko.properties#L24

Please use the actual names of the APMs in all languages strings, and respect the case of the brand.

Example in this file:
"cko.bancontact.name" should have the value "Bancontact" and not "BANCONTACT PAY".
The actual name of each APM is available here: https://docs.checkout.com/docs/payment-methods

**Comment by michael-ugborikoko-cko** [comment]
Done

**Comment by david-fiaty-cko** [comment]
@michael-ugborikoko-cko, this fix is still missing for other languages.
Example: 
https://github.com/checkout/link_checkoutcom/blob/939f7d2808a046afe6764af585318adb41b405d1/Cartridges/int_checkoutcom/cartridge/templates/resources/cko_es.properties#L25

Please check all files.

**Comment by michael-ugborikoko-cko** [comment]
Done

**Comment by michael-ugborikoko-cko** [comment]
Done
